version: '3'
services:
    nginxpadel:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        image: nginx/laravel
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '71:80'
        volumes:
            - '.:/usr/share/nginx/html'
            - './docker/nginx/sites-available:/etc/nginx/conf.d'
        networks:
            - dev-network
        depends_on:
            - phppadel
    phppadel:
        build:
            context: ./docker/php8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: php-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-6174}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - dev-network
networks: 
    dev-network:
        external: true
volumes:
    sail-mariadb:
        driver: local
