version: '3'
services:
    nginx-vw:
        build:
            context: ./docker/prod/nginx
            dockerfile: Dockerfile
        image: nginx/laravel
        extra_hosts:
            - "host.docker.internal:172.17.0.1"
        ports:
            - '62:80'
        volumes:
            - '.:/usr/share/nginx/html'
            - './docker/prod/nginx/sites-available:/etc/nginx/conf.d'
        networks:
            - dev-network
        depends_on:
            - php-vw
    php-vw:
        build:
            context: ./docker/prod/octane8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        extra_hosts:
            - "host.docker.internal:172.17.0.1"
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - dev-network
networks: 
    dev-network:
        external: true
volumes:
    volume-vw:
        driver: local